### ISSUE TITLE
[Suggestion] use a trait instead?

### ISSUE THREAD

**Issue by OwenMelbz** [cino/laravel-chronos#1]
Hi,

Noticed your package and liked the idea, but then I saw that we must extend your base class. 

This is a bit annoying for a couple of reasons, as it takes us away from the vanilla Laravel, it also makes it harder for PHP upgrades due to method signature changes using type hints, makes the default Laravel make:model command more complicated.

Instead it would be nicer just to apply the trait so people can clearly see, e.g.

```php
class Person extends Model
{
    use Chronos;
}
```

Another argument that is going around is “composition over inheritance” which suggests applying functionality as needed via traits and constructors rather than having big base classes that things all extend from.

Hopefully this will be something you’d consider! Maybe even make it an option to either extend OR trait!?

Thanks :)

**Comment by cino** [comment]
Hi Owen, 

First of all thanks for taking the time and checking out this repo, much appreciated!

All I can say is I agree with what your saying and will be adding support for using a trait instead of extending :)

**Comment by cino** [comment]
This feature has been added in v1.1.0, thanks again for the feedback!
